### ISSUE TITLE
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method

### ISSUE THREAD

**Issue by lizhixi212** [leffff/graphormer-pyg#10]
### bug
when run testing.ipynb
`RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
`
code：functional.py
```
from multiprocessing import Pool
def batched_shortest_path_distance(data: Batch) -> Tuple[Dict[int, List[int]], Dict[int, List[int]]]:
    pool = Pool()
    relabeled_graphs = []
    shift = 0
    for graph in pool.map(to_networkx, data.to_data_list()):
        num_nodes = graph.number_of_nodes()
        relabeled_graphs.append(nx.relabel_nodes(graph, {i: i + shift for i in range(num_nodes)}))
        shift += num_nodes

    node_paths = {}
    edge_paths = {}

    for path in pool.map(all_pairs_shortest_path, relabeled_graphs):
        for k, v in path[0].items():
            node_paths[k] = v
        for k, v in path[1].items():
            edge_paths[k] = v

    return node_paths, edge_paths
```

**Comment by leffff** [comment]
Thanks for the bug report!
We will work in the compatibility of torch and multiprocessing.

For now you can just remove all the multiprocessing from for-loops and it will work

**Comment by lizhixi212** [comment]
Looking forward to your wonderful work

**Comment by leffff** [comment]
Removed multiprocessing in 1da446bcad83892d40d2cb71b47ee7f81ad25a2e, which did not really affect time complexity. Should work now. Feel free to report any bugs
