### ISSUE TITLE
Difficulty of porting pre-trained Graphormer weights to this torch geometric implementation

### ISSUE THREAD

**Issue by seyonechithrananda** [leffff/graphormer-pyg#13]
Was wondering if it was somehow possible to port the model weights from the pre-trained Graphormer models in their repo to this version somehow? Thanks for this great, simple & clear torch-geometric implementation.

**Comment by leffff** [comment]
Thanks! Well, for now it is not possible to load weights into this implementation from the official one.
However, this is a great idea. I believe that in future I will do that
