### ISSUE TITLE
Potential Bug in CentralityEncoding

### ISSUE THREAD

**Issue by AjSiciliano** [leffff/graphormer-pyg#16]
<img width="952" alt="Screenshot 2023-09-22 at 11 30 27 AM" src="https://github.com/leffff/graphormer-pyg/assets/16036528/ac6f1408-cb33-4eca-a988-75cc8379172e">

I believe you need to add -1 to the max degrees as the shape is also max degrees. I had an edge case where if we hit the max degrees you get an index out of bounds error in "z_in/z_out", adding -1 fixed this. This could have just been an issue with my dataset but hope this helps! I attached the two lines I changed in a screen shot (#UPDATE). 

Aj

**Comment by leffff** [comment]
Tnanks! I'll soon take a closer look

**Comment by leffff** [comment]
Hey! It took me a while to get back to the project!
I have added your changes! Thanks a lot! 
d3d5b45d1bb87e5883a5b370c6f464f944f61634
